"""
Build analyst_exercise.ipynb programmatically using nbformat.

Run: python build_notebook.py
"""
from pathlib import Path

import nbformat as nbf

nb = nbf.v4.new_notebook()
nb.metadata["kernelspec"] = {
    "display_name": "Python 3",
    "language": "python",
    "name": "python3",
}


def md(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(src)


def code(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(src)


# ─────────────────────────────────────────────────────────────────────────────
# Cell 1 — Title + Executive Summary
# ─────────────────────────────────────────────────────────────────────────────
C1 = md(
    "# SCE Timed Analyst Exercise — Puente Hills, CA (TOU-GS-2 Option D)\n\n"
    "**Customer:** Anonymized commercial, **Puente Hills, CA** "
    "(SCE service territory).\n"
    "*Note:* the raw CSV lists an Ontario, CA address but Mike confirmed "
    "the actual site is in Puente Hills. Both are in the same SCE service "
    "area and the same NREL climate zone, so results are unchanged; the "
    "location is called out for the PV assumption (Q7).\n\n"
    "**Tariff:** TOU-GS-2 Option D (small/medium business, 20–200 kW)\n"
    "**Data:** UtilityAPI 15-min intervals, calendar year 2024\n"
    "**Tool:** Python (pandas, numpy, matplotlib) in Jupyter Notebook. "
    "All helper logic in `helpers.py` (self-contained, ~500 LOC).\n\n"
    "---\n\n"
    "## Two headline assumptions (please read first)\n\n"
    "1. **Rates:** I applied the **Jan 1, 2025** tariff rates (from the "
    "provided PDF, Advice 5449-E) to 2024 usage data. Actual 2024 billing "
    "would use the rates that were in effect during that period, which "
    "differ by a few percent. Using the provided rates as the "
    "prescriptive answer.\n"
    "2. **TOU period stability:** The current **4pm–9pm on-peak / "
    "mid-peak** window structure has been effective since **March 2019** "
    "(SCE Advice 3957-E). So the TOU period definitions apply "
    "consistently across all of 2024.\n\n"
    "---\n\n"
    "## Table of Contents\n"
    "1. Data loading and sanity checks\n"
    "2. **Q1** — Monthly peak demand\n"
    "3. **Q2** — Peak demand in priced windows\n"
    "4. **Q3** — Monthly energy use\n"
    "5. **Q4** — Energy by TOU period\n"
    "6. **Q5** — Monthly SCE bill (demand vs energy split)\n"
    "7. **Q6** — HVAC energy fraction (methodology + estimate)\n"
    "8. **Q7** — 300 kW PV impact on Q1–Q5\n"
    "9. **Q8** — 250 kWh battery impact on Q1–Q5\n"
    "10. Summary and next steps\n\n"
    "## How I approached this\n"
    "- Read all task documents carefully before touching code\n"
    "- Identified critical technical points: `interval_kWh` (not kW), "
    "descending time order, 4 TOU periods (not 3), two independent demand "
    "charges (FRD year-round + TRD seasonal weekdays)\n"
    "- Built a self-contained folder that can be zipped and re-run "
    "standalone (no dependency on any wider codebase)\n"
    "- Prioritized Q1–Q5 (numerical) and treated Q6–Q8 as methodology "
    "walkthroughs with first-order estimates\n\n"
    "## Key assumptions (also called out inline)\n"
    "- Bundled Service (Delivery + SCE Generation)\n"
    "- Standard voltage tier (2–50 kV), no voltage discount\n"
    "- Option D standard (no CPP enrollment)\n"
    "- No CARE / Climate Credit / Food Bank discount\n"
    "- Tariff rates effective Jan 1, 2025 (attached PDF). For 2024 the "
    "actual rates were ~2–5% lower. I use the attached rates as instructed.\n"
    "- Q6/Q7: use synthetic proxies for temp/PV; real answer needs external "
    "data (NOAA + PVWatts). Documented explicitly.\n"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 2 — Setup and imports
# ─────────────────────────────────────────────────────────────────────────────
C2 = code(
    "import matplotlib\n"
    "try:\n"
    "    get_ipython().run_line_magic('matplotlib', 'inline')\n"
    "except Exception:\n"
    "    matplotlib.use('Agg')\n\n"
    "import json\n"
    "import warnings\n"
    "from pathlib import Path\n\n"
    "import matplotlib.pyplot as plt\n"
    "import numpy as np\n"
    "import pandas as pd\n\n"
    "warnings.filterwarnings('ignore')\n"
    "pd.set_option('display.width', 120)\n"
    "pd.set_option('display.max_columns', 20)\n"
    "plt.rcParams['figure.dpi'] = 90\n\n"
    "from helpers import (\n"
    "    apply_real_solar,\n"
    "    bill_from_scenario,\n"
    "    calculate_monthly_bill,\n"
    "    classify_periods_vec,\n"
    "    is_holiday,\n"
    "    is_trd_hour,\n"
    "    load_and_clean_data,\n"
    "    load_real_solar,\n"
    "    load_real_weather,\n"
    "    load_tariff,\n"
    "    simulate_battery,\n"
    "    simulate_battery_milp,\n"
    "    simulate_solar,\n"
    ")\n\n"
    "CSV = Path('data_test') / 'intervals_1000000001.csv'\n"
    "print(f'Working directory: {Path().resolve()}')\n"
    "print(f'CSV exists: {CSV.exists()}')"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 3 — Section 1 header
# ─────────────────────────────────────────────────────────────────────────────
C3 = md(
    "## Section 1 — Data Loading and Sanity Checks\n\n"
    "**Tool:** pandas.\n\n"
    "**Steps applied by `load_and_clean_data()`:**\n"
    "1. Parse `interval_start` as datetime (US/Pacific)\n"
    "2. Sort ascending (raw CSV is in descending order)\n"
    "3. Convert `interval_kWh` → `demand_kw` via ×4 (15-min interval)\n"
    "4. Slice to `2024-01-01 → 2024-12-31`\n"
    "5. Add `month`, `day_of_week`, `hour`, `is_weekend`, `date` columns\n\n"
    "**Sanity checks:** row count (expect 35,136 = 366 days × 96), date "
    "range, gap detection, duplicate timestamps."
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 4 — Load and check data
# ─────────────────────────────────────────────────────────────────────────────
C4 = code(
    "df = load_and_clean_data(CSV, year=2024)\n"
    "df['tou_period'] = classify_periods_vec(df['timestamp'])\n"
    "df['is_trd'] = df['timestamp'].apply(is_trd_hour)\n\n"
    "print('Row count:            ', len(df))\n"
    "print('Expected (leap year): ', 366 * 96)\n"
    "print('Date range:           ', df['timestamp'].min(),\n"
    "      '->', df['timestamp'].max())\n"
    "print('Peak demand:          ', f\"{df['demand_kw'].max():.1f} kW\")\n"
    "print('Mean demand:          ', f\"{df['demand_kw'].mean():.1f} kW\")\n"
    "print('Annual energy:        ',\n"
    "      f\"{df['interval_kwh'].sum():,.0f} kWh\")\n"
    "print()\n\n"
    "# Duplicate + gap check\n"
    "dup_count = df.duplicated(subset='timestamp').sum()\n"
    "print(f'Duplicate timestamps: {dup_count}')\n"
    "ts_sorted = df['timestamp'].sort_values().reset_index(drop=True)\n"
    "gaps = ts_sorted.diff().dropna()\n"
    "gap_summary = gaps.value_counts().head(3)\n"
    "print('Interval spacing:')\n"
    "for span, cnt in gap_summary.items():\n"
    "    print(f'  {span}: {cnt}')\n\n"
    "df.head(3)"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 5 — Q1 header
# ─────────────────────────────────────────────────────────────────────────────
C5 = md(
    "## Q1 — Monthly Peak Demand\n\n"
    "> *What is the peak demand for each month?*\n\n"
    "**Tool:** pandas `groupby('month').agg({'demand_kw': 'max'})`.\n\n"
    "**Definition:** peak demand = maximum 15-min average kW in the "
    "calendar month.  This is the Facilities-Related Demand (FRD) billing "
    "quantity per SCE Special Condition 6.\n\n"
    "**Assumption:** meter interval matches SCE's 15-min billing "
    "interval — confirmed from `interval_start`/`interval_end` in the raw CSV."
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 6 — Q1 code
# ─────────────────────────────────────────────────────────────────────────────
C6 = code(
    "peak_idx = df.groupby('month')['demand_kw'].idxmax()\n"
    "q1 = pd.DataFrame({\n"
    "    'peak_kw': df.loc[peak_idx, 'demand_kw'].round(1).values,\n"
    "    'peak_time': df.loc[peak_idx, 'timestamp'].values,\n"
    "}, index=peak_idx.index)\n"
    "q1.index.name = 'month'\n"
    "print('Q1 — Monthly peak demand (2024):')\n"
    "print(q1)\n"
    "print(f\"\\nAnnual peak: {q1['peak_kw'].max():.1f} kW on \"\n"
    "      f\"{q1.loc[q1['peak_kw'].idxmax(), 'peak_time']}\")\n\n"
    "fig, ax = plt.subplots(figsize=(10, 3.5))\n"
    "ax.bar(q1.index, q1['peak_kw'], color='#1976D2')\n"
    "for m, v in zip(q1.index, q1['peak_kw']):\n"
    "    ax.text(m, v + 3, f'{v:.0f}', ha='center', fontsize=8)\n"
    "ax.set_xlabel('Month')\n"
    "ax.set_ylabel('Peak demand (kW)')\n"
    "ax.set_title('Q1 - Monthly Peak Demand, 2024')\n"
    "ax.set_xticks(range(1, 13))\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 7 — Q2 header
# ─────────────────────────────────────────────────────────────────────────────
C7 = md(
    "## Q2 — Peak Demand in Priced Windows\n\n"
    "> *Peak during summer On-Peak (each summer month) and winter "
    "Mid-Peak (each winter month).*\n\n"
    "**Tool:** pandas boolean masking + `groupby('month').max()`.\n\n"
    "**Interpretation:** these are the **TRD** (Time-Related Demand) "
    "billing quantities — the peaks that drive the seasonal $/kW charges.\n\n"
    "- Summer On-Peak: weekdays 4–9 PM, June–September (excl. holidays)\n"
    "- Winter Mid-Peak: weekdays 4–9 PM, October–May (excl. holidays)\n\n"
    "Weekends and holidays never count toward TRD (per SCE Special "
    "Condition 1)."
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 8 — Q2 code
# ─────────────────────────────────────────────────────────────────────────────
C8 = code(
    "trd_df = df[df['is_trd']].copy()\n\n"
    "trd_idx = trd_df.groupby('month')['demand_kw'].idxmax()\n"
    "q2 = pd.DataFrame({\n"
    "    'peak_kw': trd_df.loc[trd_idx, 'demand_kw'].round(1).values,\n"
    "    'peak_time': trd_df.loc[trd_idx, 'timestamp'].values,\n"
    "}, index=trd_idx.index)\n"
    "q2.index.name = 'month'\n"
    "q2['window'] = q2.index.map(\n"
    "    lambda m: 'Summer On-Peak' if m in (6, 7, 8, 9)\n"
    "              else 'Winter Mid-Peak'\n"
    ")\n"
    "print('Q2 - TRD peak demand by month (2024):')\n"
    "print(q2[['window', 'peak_kw', 'peak_time']])\n\n"
    "# Plot showing FRD (all-time) vs TRD (windowed) for comparison\n"
    "fig, ax = plt.subplots(figsize=(10, 3.5))\n"
    "w = 0.4\n"
    "ax.bar(q1.index - w/2, q1['peak_kw'], w,\n"
    "       label='FRD peak (all hours)', color='#455A64')\n"
    "ax.bar(q2.index + w/2, q2['peak_kw'], w,\n"
    "       label='TRD peak (priced window only)', color='#E64A19')\n"
    "ax.set_xlabel('Month')\n"
    "ax.set_ylabel('Peak demand (kW)')\n"
    "ax.set_title('Q2 - FRD vs TRD Peaks')\n"
    "ax.legend(loc='upper left', fontsize=9)\n"
    "ax.set_xticks(range(1, 13))\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 9 — Q3 header
# ─────────────────────────────────────────────────────────────────────────────
C9 = md(
    "## Q3 — Total Monthly Energy\n\n"
    "> *Total energy in each month.*\n\n"
    "**Tool:** pandas `groupby('month')['interval_kwh'].sum()`.\n\n"
    "Straight sum of `interval_kWh` per month. Sanity check against Q1: "
    "the annual total should equal `sum(interval_kWh)` and roughly "
    "equal mean_kW × 8784 hours (leap year)."
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 10 — Q3 code
# ─────────────────────────────────────────────────────────────────────────────
C10 = code(
    "q3 = df.groupby('month')['interval_kwh'].sum().round(0)\n"
    "q3.name = 'energy_kwh'\n"
    "print('Q3 - Monthly energy (2024):')\n"
    "for m, kwh in q3.items():\n"
    "    print(f'  Month {m:02d}: {kwh:>10,.0f} kWh')\n"
    "print(f\"\\nAnnual total: {q3.sum():,.0f} kWh \"\n"
    "      f\"({q3.sum()/1e6:.2f} GWh)\")\n"
    "print(f\"Sanity: mean_kW * 8784 h = \"\n"
    "      f\"{df['demand_kw'].mean() * 8784:,.0f} kWh\")\n\n"
    "fig, ax = plt.subplots(figsize=(10, 3.5))\n"
    "ax.bar(q3.index, q3.values, color='#388E3C')\n"
    "for m, v in zip(q3.index, q3.values):\n"
    "    ax.text(m, v + q3.max() * 0.01, f'{v/1000:.0f}k',\n"
    "            ha='center', fontsize=8)\n"
    "ax.set_xlabel('Month')\n"
    "ax.set_ylabel('Energy (kWh)')\n"
    "ax.set_title('Q3 - Monthly Energy Use, 2024')\n"
    "ax.set_xticks(range(1, 13))\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 11 — Q4 header
# ─────────────────────────────────────────────────────────────────────────────
C11 = md(
    "## Q4 — Energy by TOU Period per Month\n\n"
    "> *Total energy in each TOU period for each month.*\n\n"
    "**Tool:** pandas pivot table.\n\n"
    "For TOU-GS-2 Option D the periods are Super-Off-Peak, Off-Peak, "
    "Mid-Peak, On-Peak. Not all periods exist in every month/day-type:\n"
    "- Summer weekday: On-Peak (4–9 PM), Off-Peak (everything else)\n"
    "- Summer weekend/holiday: Mid-Peak (4–9 PM), Off-Peak (all else)\n"
    "- Winter (all days): Mid-Peak (4–9 PM), Super-Off-Peak (8 AM–4 PM), "
    "Off-Peak (9 PM–8 AM)\n\n"
    "Row totals should reconcile with Q3."
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 12 — Q4 code
# ─────────────────────────────────────────────────────────────────────────────
C12 = code(
    "q4 = df.pivot_table(\n"
    "    index='month',\n"
    "    columns='tou_period',\n"
    "    values='interval_kwh',\n"
    "    aggfunc='sum',\n"
    "    fill_value=0,\n"
    ").round(0)\n\n"
    "# Reorder columns and add total\n"
    "period_order = ['super_off_peak', 'off_peak', 'mid_peak', 'on_peak']\n"
    "period_order = [p for p in period_order if p in q4.columns]\n"
    "q4 = q4[period_order]\n"
    "q4['total'] = q4.sum(axis=1)\n"
    "print('Q4 - Monthly energy by TOU period (kWh):')\n"
    "print(q4)\n\n"
    "# Verify against Q3\n"
    "print(f\"\\nReconciliation with Q3: max diff = \"\n"
    "      f\"{(q4['total'] - q3).abs().max():.0f} kWh\")\n\n"
    "# Stacked bar chart\n"
    "colors = {'super_off_peak': '#7BC67E', 'off_peak': '#B0BEC5',\n"
    "         'mid_peak': '#F9A825', 'on_peak': '#C62828'}\n"
    "fig, ax = plt.subplots(figsize=(11, 4))\n"
    "bottom = np.zeros(12)\n"
    "for p in period_order:\n"
    "    vals = q4[p].values\n"
    "    ax.bar(q4.index, vals, bottom=bottom, label=p,\n"
    "           color=colors.get(p, 'gray'))\n"
    "    bottom = bottom + vals\n"
    "ax.set_xlabel('Month')\n"
    "ax.set_ylabel('Energy (kWh)')\n"
    "ax.set_title('Q4 - Energy by TOU Period per Month')\n"
    "ax.legend(fontsize=9)\n"
    "ax.set_xticks(range(1, 13))\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 13 — Q5 header
# ─────────────────────────────────────────────────────────────────────────────
C13 = md(
    "## Q5 — Monthly SCE Bill (Demand vs Energy Split)\n\n"
    "> *How much does the customer pay each month? How much is demand vs "
    "energy?*\n\n"
    "**Tool:** custom `calculate_monthly_bill()` in `helpers.py`, "
    "using rates from `sce_tou_gs2d.json`.\n\n"
    "**Bill components for TOU-GS-2 Option D:**\n"
    "1. **Energy charge** = Σ (kWh_in_period × $/kWh rate for that period)\n"
    "2. **FRC + MCAM** = kWh_total × (0.00153 + 0.00124) $/kWh riders\n"
    "3. **FRD (Facilities-Related Demand)** = peak_kW_any_time × $24.86/kW\n"
    "4. **TRD (Time-Related Demand)** = peak_kW_in_TRD_hours × $/kW rate\n"
    "   ($36.33 summer, $7.82 winter)\n"
    "5. **Customer charge** = $237.85/month fixed\n\n"
    "**Q5a — Demand portion** = FRD + TRD\n"
    "**Q5b — Energy portion** = Energy charge + FRC/MCAM + Customer charge"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 14 — Q5 code
# ─────────────────────────────────────────────────────────────────────────────
C14 = code(
    "tariff = load_tariff()\n"
    "bill = calculate_monthly_bill(df, tariff)\n\n"
    "print('Q5 - Monthly bill breakdown (2024):')\n"
    "print(bill[['energy_kwh', 'peak_demand_kw', 'trd_peak_kw',\n"
    "           'energy_charge_usd', 'frc_mcam_usd',\n"
    "           'frd_charge_usd', 'trd_charge_usd',\n"
    "           'customer_charge_usd', 'total_usd']].round(0))\n\n"
    "annual_total = bill['total_usd'].sum()\n"
    "annual_demand = bill['demand_portion_usd'].sum()\n"
    "annual_energy = bill['energy_portion_usd'].sum()\n"
    "print()\n"
    "print(f'ANNUAL TOTAL:  ${annual_total:>10,.0f}')\n"
    "print(f'  Demand:      ${annual_demand:>10,.0f}  '\n"
    "      f'({100*annual_demand/annual_total:.1f}%)')\n"
    "print(f'  Energy:      ${annual_energy:>10,.0f}  '\n"
    "      f'({100*annual_energy/annual_total:.1f}%)')\n\n"
    "# Bill stacked bar chart\n"
    "fig, ax = plt.subplots(figsize=(11, 4))\n"
    "months_idx = bill.index\n"
    "energy_bar   = bill['energy_charge_usd'] + bill['frc_mcam_usd']\n"
    "frd_bar      = bill['frd_charge_usd']\n"
    "trd_bar      = bill['trd_charge_usd']\n"
    "customer_bar = bill['customer_charge_usd']\n"
    "ax.bar(months_idx, energy_bar, label='Energy (kWh)', color='#78909C')\n"
    "ax.bar(months_idx, frd_bar, bottom=energy_bar,\n"
    "       label='FRD (all-time demand)', color='#EF6C00')\n"
    "ax.bar(months_idx, trd_bar, bottom=energy_bar + frd_bar,\n"
    "       label='TRD (window demand)', color='#C62828')\n"
    "ax.bar(months_idx, customer_bar, bottom=energy_bar + frd_bar + trd_bar,\n"
    "       label='Customer charge', color='#455A64')\n"
    "ax.set_xlabel('Month')\n"
    "ax.set_ylabel('Bill ($)')\n"
    "ax.set_title('Q5 - Monthly Bill Composition')\n"
    "ax.legend(fontsize=9)\n"
    "ax.set_xticks(range(1, 13))\n"
    "ax.yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(\n"
    "    lambda x, _: f'${x:,.0f}'))\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 15 — Q6 header
# ─────────────────────────────────────────────────────────────────────────────
C15 = md(
    "## Q6 — HVAC Fraction of Total Energy\n\n"
    "> *How much of the energy is HVAC? How would you figure that out?*\n\n"
    "**Approach:** Regress daily energy against outdoor temperature.\n\n"
    "Commercial HVAC load has two components:\n"
    "- **Baseline (non-HVAC):** lighting, plug loads, refrigeration, "
    "IT equipment — roughly constant, driven by occupancy schedule\n"
    "- **Temperature-dependent (HVAC):** cooling above a balance point "
    "(~65 °F), heating below\n\n"
    "**Model:** `daily_kWh ≈ a + b × CDD65 + c × HDD65`\n"
    "where `CDD65 = max(0, T_daily - 65)` and\n"
    "      `HDD65 = max(0, 65 - T_daily)`\n\n"
    "The HVAC fraction is `(b × Σ CDD + c × Σ HDD) / Σ daily_kWh`.\n\n"
    "**Data I would use with more time:**\n"
    "- **NOAA/NCEI ISD-Lite** hourly temperature for Ontario International "
    "Airport (station 722950), 2024\n"
    "- Alternate: NREL NSRDB TMY3 for zip 91761\n"
    "- Alternate: Meteostat API (free for hobbyists)\n\n"
    "**Fallback method used here (given time constraint):**\n"
    "Use a *synthetic temperature proxy* from the load itself — the "
    "summer-vs-winter load ratio + hour-of-day shape indicates the "
    "HVAC-driven excess. This gives a first-order estimate; a real "
    "regression on actual temperatures would tighten it substantially."
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 16 — Q6 code
# ─────────────────────────────────────────────────────────────────────────────
C16 = code(
    "# First-order estimate: baseline = min daily energy across the year\n"
    "# (usually a weekend in a shoulder month with minimal HVAC), and\n"
    "# HVAC = daily energy minus baseline.\n\n"
    "daily = df.groupby('date').agg(\n"
    "    day_kwh=('interval_kwh', 'sum'),\n"
    "    peak_kw=('demand_kw', 'max'),\n"
    ").reset_index()\n"
    "daily['month'] = pd.to_datetime(daily['date']).dt.month\n\n"
    "# Use the 10th percentile of daily energy as the baseline\n"
    "# (protects against outliers like holidays or partial closures)\n"
    "baseline_daily_kwh = daily['day_kwh'].quantile(0.10)\n"
    "print(f'Baseline (non-HVAC) daily energy estimate:'\n"
    "      f' {baseline_daily_kwh:,.0f} kWh/day')\n"
    "print(f'Peak (summer) daily energy: '\n"
    "      f'{daily[\"day_kwh\"].max():,.0f} kWh/day')\n\n"
    "daily['baseline_kwh'] = baseline_daily_kwh\n"
    "daily['hvac_kwh'] = (daily['day_kwh'] - baseline_daily_kwh).clip(lower=0)\n\n"
    "monthly = daily.groupby('month').agg(\n"
    "    total_kwh=('day_kwh', 'sum'),\n"
    "    baseline_kwh=('baseline_kwh', 'sum'),\n"
    "    hvac_kwh=('hvac_kwh', 'sum'),\n"
    ")\n"
    "monthly['hvac_pct'] = 100 * monthly['hvac_kwh'] / monthly['total_kwh']\n"
    "print()\n"
    "print('Q6 - HVAC energy estimate by month:')\n"
    "print(monthly.round(0))\n\n"
    "annual_total = monthly['total_kwh'].sum()\n"
    "annual_hvac = monthly['hvac_kwh'].sum()\n"
    "print(f'\\nEstimated annual HVAC energy: {annual_hvac:,.0f} kWh'\n"
    "      f' ({100*annual_hvac/annual_total:.1f}% of total)')\n\n"
    "# Plot\n"
    "fig, ax = plt.subplots(figsize=(11, 4))\n"
    "ax.bar(monthly.index, monthly['baseline_kwh'],\n"
    "       label='Baseline (non-HVAC)', color='#78909C')\n"
    "ax.bar(monthly.index, monthly['hvac_kwh'],\n"
    "       bottom=monthly['baseline_kwh'],\n"
    "       label='HVAC (temp-driven)', color='#EF5350')\n"
    "ax.set_xlabel('Month')\n"
    "ax.set_ylabel('Energy (kWh)')\n"
    "ax.set_title('Q6 - Estimated HVAC vs Baseline Energy '\n"
    "             '(first-order, no external temp data)')\n"
    "ax.legend(fontsize=9)\n"
    "ax.set_xticks(range(1, 13))\n"
    "plt.tight_layout()\n"
    "plt.show()\n\n"
    "print('\\n>>> CAVEAT: This is a floor estimate. A proper regression'\n"
    "      ' against hourly NOAA temperature would likely put HVAC at'\n"
    "      ' 30-45% of annual energy for a SoCal commercial building.')"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 17 — Q7 header
# ─────────────────────────────────────────────────────────────────────────────
C17 = md(
    "## Q7 — 300 kW PV Impact\n\n"
    "> *If 300 kW (AC) of behind-the-meter solar were installed, how would "
    "answers to Q1–Q5 change?*\n\n"
    "**Data needed for a rigorous answer:**\n"
    "- Hourly PV generation profile for Puente Hills, CA (approx. lat "
    "34.02°N, lon −117.94°W) from NREL PVWatts API\n"
    "- Parameters: 300 kW AC, DC/AC = 1.2, 20° tilt, 180° azimuth, 14% losses\n"
    "- NEM 3.0 export rate matrix (Net Billing Tariff) for the export "
    "portion — hourly values by month\n\n"
    "**Method used here (given time constraint):**\n"
    "A synthetic clear-sky-shaped PV profile scaled to 300 kW AC. Peak at "
    "solar noon, seasonally modulated. Sufficient for a first-order "
    "impact estimate, not for a bankable savings claim.\n\n"
    "**PV dispatch assumption:** self-consumption first — PV offsets "
    "on-site load; any excess is exported. Under NEM 3.0 (2023+) export "
    "credit is ~$0.08/kWh (wholesale-linked). For this exercise I compute "
    "the **bill reduction** without export credit (conservative)."
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 18 — Q7 code
# ─────────────────────────────────────────────────────────────────────────────
C18 = code(
    "df_solar = simulate_solar(df, system_kw_ac=300.0)\n"
    "annual_pv_kwh = df_solar['pv_kw'].sum() * 0.25\n"
    "annual_gross_load = df['interval_kwh'].sum()\n"
    "annual_net_load = df_solar['net_interval_kwh'].sum()\n"
    "annual_export = df_solar['export_interval_kwh'].sum()\n\n"
    "print(f'Annual PV generation:   {annual_pv_kwh:>10,.0f} kWh')\n"
    "print(f'Annual load (baseline): {annual_gross_load:>10,.0f} kWh')\n"
    "print(f'Annual net grid import: {annual_net_load:>10,.0f} kWh')\n"
    "print(f'Annual export to grid:  {annual_export:>10,.0f} kWh')\n"
    "print(f'Self-consumption rate:  '\n"
    "      f'{100 * (annual_pv_kwh - annual_export) / annual_pv_kwh:.1f}%')\n\n"
    "# Rebill with new net demand\n"
    "df_solar['tou_period'] = df['tou_period']\n"
    "df_solar['is_trd'] = df['is_trd']\n"
    "bill_solar = bill_from_scenario(\n"
    "    df_solar, demand_col='net_demand_kw',\n"
    "    energy_col='net_interval_kwh', tariff=tariff,\n"
    ")\n\n"
    "# Compare\n"
    "compare = pd.DataFrame({\n"
    "    'peak_kW_baseline':   bill['peak_demand_kw'].round(1),\n"
    "    'peak_kW_with_PV':    bill_solar['peak_demand_kw'].round(1),\n"
    "    'trd_kW_baseline':    bill['trd_peak_kw'].round(1),\n"
    "    'trd_kW_with_PV':     bill_solar['trd_peak_kw'].round(1),\n"
    "    'kWh_baseline':       bill['energy_kwh'].round(0),\n"
    "    'kWh_with_PV':        bill_solar['energy_kwh'].round(0),\n"
    "    'bill_baseline':      bill['total_usd'].round(0),\n"
    "    'bill_with_PV':       bill_solar['total_usd'].round(0),\n"
    "})\n"
    "compare['bill_delta'] = (compare['bill_baseline']\n"
    "                         - compare['bill_with_PV']).round(0)\n"
    "print()\n"
    "print('Q7 - PV impact on Q1-Q5:')\n"
    "print(compare)\n\n"
    "annual_savings = compare['bill_delta'].sum()\n"
    "print(f'\\nAnnual bill savings from 300 kW PV: ${annual_savings:,.0f}')\n"
    "print(f'(before any NEM 3.0 export credit)')\n\n"
    "# Chart\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
    "axes[0].bar(compare.index - 0.2, compare['peak_kW_baseline'], 0.4,\n"
    "            label='Baseline', color='#455A64')\n"
    "axes[0].bar(compare.index + 0.2, compare['peak_kW_with_PV'], 0.4,\n"
    "            label='With 300 kW PV', color='#FDD835')\n"
    "axes[0].set_xlabel('Month')\n"
    "axes[0].set_ylabel('Monthly peak demand (kW)')\n"
    "axes[0].set_title('Q7 - Peak demand: baseline vs PV')\n"
    "axes[0].legend()\n"
    "axes[0].set_xticks(range(1, 13))\n\n"
    "axes[1].bar(compare.index - 0.2, compare['bill_baseline'], 0.4,\n"
    "            label='Baseline', color='#455A64')\n"
    "axes[1].bar(compare.index + 0.2, compare['bill_with_PV'], 0.4,\n"
    "            label='With 300 kW PV', color='#FDD835')\n"
    "axes[1].set_xlabel('Month')\n"
    "axes[1].set_ylabel('Monthly bill ($)')\n"
    "axes[1].set_title('Q7 - Bill: baseline vs PV')\n"
    "axes[1].legend()\n"
    "axes[1].set_xticks(range(1, 13))\n"
    "axes[1].yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(\n"
    "    lambda x, _: f'${x:,.0f}'))\n"
    "plt.tight_layout()\n"
    "plt.show()\n\n"
    "print('\\n>>> Note: PV rarely reduces the ANNUAL peak because peaks'\n"
    "      ' often occur late afternoon (5-8 pm) when PV is already declining.'\n"
    "      ' Under the new 4-9 pm On-Peak window PV alone is not enough to'\n"
    "      ' fully shave demand charges.')"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 19 — Q8 header
# ─────────────────────────────────────────────────────────────────────────────
C19 = md(
    "## Q8 — 250 kWh Battery Impact\n\n"
    "> *If a 250 kWh battery were installed BTM, how would Q1–Q5 change?*\n\n"
    "### Battery sizing decision\n\n"
    "The task specifies **250 kWh** of storage but not the kW (inverter) "
    "rating. I looked at the load duration curve first to size the "
    "inverter for this customer:\n\n"
    "| Threshold | Hours/yr above |\n"
    "|---|---|\n"
    "| Peak − 25 kW  (~265 kW) | 8 hr |\n"
    "| Peak − 50 kW  (~240 kW) | 78 hr |\n"
    "| Peak − 100 kW (~190 kW) | 757 hr |\n"
    "| Peak − 125 kW (~165 kW) | 1,247 hr |\n\n"
    "The peaks are broad plateaus, not sharp spikes. A shorter-duration "
    "battery (125 kW / 2-hr) drains before the plateau ends, leaving the "
    "monthly peak nearly unchanged. A longer-duration battery (50 kW / "
    "5-hr) sustains through the whole evening but only shaves 50 kW.\n\n"
    "**Choice: 250 kWh / 100 kW (2.5-hr).** Middle ground: shaves up to "
    "100 kW off the peak while sustaining through ~2 hours of the 4-9 PM "
    "window. Any residual discharge on the shoulders further reduces the "
    "TRD peak.\n\n"
    "### Assumptions\n"
    "- **Capacity:** 250 kWh (as given)\n"
    "- **Power rating:** **100 kW** (inverter, 2.5-hr duration)\n"
    "- **Round-trip efficiency:** 90% (LFP typical)\n"
    "- **Depth of Discharge:** 100% (all 250 kWh usable)\n\n"
    "### Dispatch strategy (rule-based)\n"
    "- **Discharge:** full 100 kW whenever load is within 100 kW of the "
    "monthly peak (widened from 4-9 PM only, because the actual peak in "
    "this data occurs at 2:30 PM on Sep 9 — outside the on-peak window). "
    "This shaves both FRD and TRD peaks simultaneously.\n"
    "- **Charge:** overnight (0-8 AM) and, in winter, super-off-peak "
    "(8 AM-4 PM). Never charge fast enough to set a new monthly peak "
    "(safety check against 60th-percentile ceiling).\n\n"
    "### Why not MILP + load forecasting?\n\n"
    "A rule-based full-100 kW discharge is a **first-order lower bound**. "
    "With more time the proper approach is:\n"
    "1. **Load forecasting** — predict next 24 h demand from historical + "
    "temperature + calendar features (ARIMA / gradient boosting)\n"
    "2. **MILP dispatch** — with the forecast in hand, solve for optimal "
    "hourly (or 15-min) charge/discharge that minimizes monthly bill "
    "subject to SoC/power/TOU constraints (`cvxpy` + HIGHS or GLPK_MI)\n"
    "3. **Rolling horizon** — re-solve every day at 10am with fresh "
    "forecasts. Real deployments cover 80–90% of the perfect-foresight "
    "MILP upper bound.\n\n"
    "With load forecasting the battery would discharge selectively: hold "
    "SoC in reserve for the true evening peak (rather than exhausting it "
    "on any near-peak interval), which is why a smart-dispatch answer is "
    "typically **2–5× larger** than this rule-based floor."
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 20 — Q8 code
# ─────────────────────────────────────────────────────────────────────────────
C20 = code(
    "df_bat = simulate_battery(df, capacity_kwh=250, power_kw=100,\n"
    "                          efficiency=0.90)\n"
    "df_bat['tou_period'] = df['tou_period']\n"
    "df_bat['is_trd'] = df['is_trd']\n\n"
    "annual_discharge = df_bat.loc[df_bat['battery_kw'] > 0,\n"
    "                              'battery_kw'].sum() * 0.25\n"
    "annual_charge = -df_bat.loc[df_bat['battery_kw'] < 0,\n"
    "                            'battery_kw'].sum() * 0.25\n"
    "print(f'Annual battery discharge: {annual_discharge:>7,.0f} kWh')\n"
    "print(f'Annual battery charge:    {annual_charge:>7,.0f} kWh')\n"
    "print(f'Round-trip efficiency:    '\n"
    "      f'{100 * annual_discharge / annual_charge:.1f}%')\n\n"
    "# Rebill with battery\n"
    "bill_bat = bill_from_scenario(\n"
    "    df_bat, demand_col='net_demand_kw',\n"
    "    energy_col='net_interval_kwh', tariff=tariff,\n"
    ")\n\n"
    "compare_bat = pd.DataFrame({\n"
    "    'peak_kW_baseline':   bill['peak_demand_kw'].round(1),\n"
    "    'peak_kW_with_bat':   bill_bat['peak_demand_kw'].round(1),\n"
    "    'trd_kW_baseline':    bill['trd_peak_kw'].round(1),\n"
    "    'trd_kW_with_bat':    bill_bat['trd_peak_kw'].round(1),\n"
    "    'kWh_baseline':       bill['energy_kwh'].round(0),\n"
    "    'kWh_with_bat':       bill_bat['energy_kwh'].round(0),\n"
    "    'bill_baseline':      bill['total_usd'].round(0),\n"
    "    'bill_with_bat':      bill_bat['total_usd'].round(0),\n"
    "})\n"
    "compare_bat['bill_delta'] = (compare_bat['bill_baseline']\n"
    "                             - compare_bat['bill_with_bat']).round(0)\n"
    "print()\n"
    "print('Q8 - Battery impact on Q1-Q5:')\n"
    "print(compare_bat)\n\n"
    "annual_bat_savings = compare_bat['bill_delta'].sum()\n"
    "print(f'\\nAnnual bill savings from 250 kWh battery: '\n"
    "      f'${annual_bat_savings:,.0f}')\n"
    "print('(rule-based dispatch — MILP would yield 2-5x more)')\n\n"
    "# Chart\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
    "axes[0].bar(compare_bat.index - 0.2, compare_bat['peak_kW_baseline'],\n"
    "            0.4, label='Baseline', color='#455A64')\n"
    "axes[0].bar(compare_bat.index + 0.2, compare_bat['peak_kW_with_bat'],\n"
    "            0.4, label='With 250 kWh battery', color='#26A69A')\n"
    "axes[0].set_xlabel('Month')\n"
    "axes[0].set_ylabel('Peak demand (kW)')\n"
    "axes[0].set_title('Q8 - Peak demand: baseline vs battery')\n"
    "axes[0].legend()\n"
    "axes[0].set_xticks(range(1, 13))\n\n"
    "axes[1].bar(compare_bat.index - 0.2, compare_bat['bill_baseline'], 0.4,\n"
    "            label='Baseline', color='#455A64')\n"
    "axes[1].bar(compare_bat.index + 0.2, compare_bat['bill_with_bat'], 0.4,\n"
    "            label='With battery', color='#26A69A')\n"
    "axes[1].set_xlabel('Month')\n"
    "axes[1].set_ylabel('Monthly bill ($)')\n"
    "axes[1].set_title('Q8 - Bill: baseline vs battery')\n"
    "axes[1].legend()\n"
    "axes[1].set_xticks(range(1, 13))\n"
    "axes[1].yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(\n"
    "    lambda x, _: f'${x:,.0f}'))\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# ─────────────────────────────────────────────────────────────────────────────
# Cell 21 — Summary + next steps
# ─────────────────────────────────────────────────────────────────────────────
C21 = md(
    "## Section 10 — Summary and Next Steps\n\n"
    "### Final answers (2024, Puente Hills CA, TOU-GS-2 Option D)\n\n"
    "| Q | Headline answer |\n"
    "|---|---|\n"
    "| **Q1** Peak demand | Range 173–291 kW across months; "
    "annual peak **290.9 kW on 2024-09-09 at 14:30** |\n"
    "| **Q2** TRD peaks | Summer On-Peak (Jun–Sep) drives the "
    "expensive TRD $ (~$36.33/kW); winter Mid-Peak much lower "
    "(~$7.82/kW) |\n"
    "| **Q3** Monthly energy | 78–112 MWh/mo, **annual 1.09 GWh** |\n"
    "| **Q4** Energy by TOU | Off-Peak dominates; Super-Off-Peak "
    "meaningful in winter; On-Peak surprisingly small |\n"
    "| **Q5** Bill | **Annual $257,798**; demand ~35% / energy ~65% |\n"
    "| **Q6** HVAC (first-order) | ~25% via 10th-percentile baseline "
    "(upper bound floor estimate) |\n"
    "| **Q6b** HVAC (regression) | **6.0%** via CDD65 + HDD65 fit — "
    "surprising, suggests industrial baseline dominates |\n"
    "| **Q7** 300 kW PV (synthetic) | ~$83k/yr bill reduction |\n"
    "| **Q7b** 300 kW PV (real profile) | **$75,214 billed + $4,031 "
    "NEM export = $79,245/yr total** |\n"
    "| **Q8** 250 kWh battery (rule-based) | **$224/yr** — peak-shave "
    "floor (rule-based dispatch is myopic) |\n"
    "| **Q8b** 250 kWh battery (MILP) | **$31,011/yr — 138× "
    "rule-based** — proves MILP as the true upper bound |\n\n"
    "### Surprising findings worth flagging\n\n"
    "1. **HVAC is only 6% of load, not the typical 30-40% for a "
    "commercial building.** The load-vs-temperature slope is small "
    "(30 kWh/CDD, negative HDD). This site likely has significant "
    "non-HVAC industrial or refrigeration baseline. Worth asking the "
    "customer about their process loads.\n"
    "2. **Annual peak (290.9 kW) occurs at 14:30**, not during "
    "on-peak hours (4-9 PM). That means the FRD peak is driven by "
    "an equipment startup or process spike, not by HVAC + typical "
    "afternoon load. A battery dispatch that only discharges 4-9 PM "
    "would miss this peak entirely — hence the enormous gap between "
    "rule-based ($224) and MILP ($31k) results.\n"
    "3. **MILP delivers 138× more value than the rule-based** "
    "dispatch. Real-world deployments with rolling forecasts "
    "typically capture 80–90% of this MILP optimum — so a realistic "
    "battery savings ballpark is ~$25k/yr, not $224.\n\n"
    "### What I would do with more time\n\n"
    "**Data quality**\n"
    "1. Cross-check the computed bill against actual SCE invoices "
    "for a few months\n"
    "2. Multi-year analysis — data spans Apr 2023 to Feb 2025; "
    "compare year-over-year trends\n"
    "3. Investigate the 14:30 Sep-9 peak (Q1) — is it a process "
    "spike we can control?\n\n"
    "**HVAC (Q6/Q6b)**\n"
    "1. Add sub-hourly weather to catch peak-hour temp effects "
    "(daily average may hide brief hot spikes)\n"
    "2. Break the load into occupied vs unoccupied hours; the true "
    "HVAC fraction may be higher during business hours\n"
    "3. Cross-check against NREL ComStock benchmark for the likely "
    "building type (SoCal climate zone 10)\n\n"
    "**PV (Q7/Q7b)**\n"
    "1. Use the **SCE NEM 3.0 hourly export rate matrix** instead "
    "of the flat $0.08/kWh proxy\n"
    "2. Optimize panel orientation: **west-facing tilt** pushes more "
    "generation into 4–9 PM on-peak, boosting demand-charge savings\n"
    "3. Sensitivity: PV size sweep 100–500 kW to find the "
    "diminishing-returns knee\n\n"
    "**Battery (Q8/Q8b)**\n"
    "1. Add **binary switch variables** to make the LP a proper "
    "MILP (prevents any theoretical simultaneous charge+discharge)\n"
    "2. Combine PV + battery in a **joint MILP** — typically beats "
    "sequential optimization by 10–20%\n"
    "3. Rolling-horizon MPC with load & solar forecasting — "
    "captures 80–90% of the perfect-foresight upper bound\n"
    "4. Model **degradation** (cycle counting + capacity fade) "
    "over 10-15 year investment horizon\n\n"
    "**Rate optimization**\n"
    "1. Compare Option D vs Option E for this specific load shape "
    "(Option E has lower demand $/kW, higher energy $/kWh — could "
    "flip the economics for a low-demand-factor load like this one)\n"
    "2. Model Option D-CPP with realistic 12–15 CPP events/year\n"
    "3. If peak trends above 200 kW consistently, check TOU-GS-3 "
    "eligibility\n\n"
    "### Reflection on the exercise\n\n"
    "The most interesting insight came from the load-vs-temperature "
    "regression: the load doesn't behave like a typical commercial "
    "building. The 6% HVAC figure combined with a 14:30 annual peak "
    "hints at process/industrial loads that aren't captured by the "
    "traditional 'HVAC + lighting + plug' decomposition. In a real "
    "engagement I would prioritize a site walkthrough or sub-metering "
    "conversation to identify the driver of that mid-day spike — "
    "that's likely where the biggest DER optimization lever lives.\n\n"
    "---\n"
    "*All source in this folder. Contact me with any questions about "
    "assumptions or methodology.*\n"
)

# ═════════════════════════════════════════════════════════════════════════════
# NEW CELLS: real-data + MILP additions
# ═════════════════════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────────────────────────────────────
# C16b - Q6b markdown: HVAC via real weather regression
# ─────────────────────────────────────────────────────────────────────────────
C16b_md = md(
    "### Q6b — HVAC via real weather regression\n\n"
    "Above I estimated HVAC as a first-order lower bound. Now that we have "
    "**hourly weather data** for Puente Hills 2024, we can do a proper "
    "change-point regression:\n\n"
    "**Model:** `daily_kWh = a + b × CDD65 + c × HDD65`\n\n"
    "- `CDD65 = max(0, T_daily_avg − 65°F)` — cooling degree days\n"
    "- `HDD65 = max(0, 65°F − T_daily_avg)` — heating degree days\n"
    "- Coefficients `b` and `c` are marginal kWh per degree-day (HVAC "
    "sensitivity)\n"
    "- Intercept `a` is the temperature-independent baseline load\n\n"
    "**HVAC fraction** = `(b × Σ CDD + c × Σ HDD) / Σ daily_kWh`\n\n"
    "This is the standard method used in commercial energy audits."
)

# ─────────────────────────────────────────────────────────────────────────────
# C16c - Q6b code: real weather regression
# ─────────────────────────────────────────────────────────────────────────────
C16c_code = code(
    "weather = load_real_weather()\n"
    "weather['date'] = weather['timestamp'].dt.date\n"
    "daily_temp = weather.groupby('date').agg(\n"
    "    temp_f_avg=('temp_f', 'mean'),\n"
    "    temp_f_max=('temp_f', 'max'),\n"
    "    temp_f_min=('temp_f', 'min'),\n"
    ").reset_index()\n\n"
    "# Combine with daily load\n"
    "daily_full = daily.merge(daily_temp, on='date', how='left')\n"
    "daily_full['cdd65'] = (daily_full['temp_f_avg'] - 65).clip(lower=0)\n"
    "daily_full['hdd65'] = (65 - daily_full['temp_f_avg']).clip(lower=0)\n\n"
    "# Regression: day_kwh = a + b*CDD + c*HDD\n"
    "from numpy.linalg import lstsq\n"
    "X = np.column_stack([\n"
    "    np.ones(len(daily_full)),\n"
    "    daily_full['cdd65'].values,\n"
    "    daily_full['hdd65'].values,\n"
    "])\n"
    "y = daily_full['day_kwh'].values\n"
    "coefs, _, _, _ = lstsq(X, y, rcond=None)\n"
    "a, b, c = coefs\n"
    "print(f'Regression fit (daily_kwh ~ a + b*CDD65 + c*HDD65):')\n"
    "print(f'  a (baseline)  = {a:>8,.1f} kWh/day  (temp-independent load)')\n"
    "print(f'  b (CDD slope) = {b:>8.1f} kWh/degree-day (cooling)')\n"
    "print(f'  c (HDD slope) = {c:>8.1f} kWh/degree-day (heating)')\n\n"
    "# HVAC fraction of total\n"
    "cooling_kwh = b * daily_full['cdd65'].sum()\n"
    "heating_kwh = c * daily_full['hdd65'].sum()\n"
    "baseline_kwh = a * len(daily_full)\n"
    "total_kwh = daily_full['day_kwh'].sum()\n"
    "hvac_frac = (cooling_kwh + heating_kwh) / total_kwh\n\n"
    "print()\n"
    "print(f'Annual decomposition:')\n"
    "print(f'  Baseline (non-HVAC): {baseline_kwh:>10,.0f} kWh '\n"
    "      f'({100*baseline_kwh/total_kwh:.1f}%)')\n"
    "print(f'  Cooling (CDD):       {cooling_kwh:>10,.0f} kWh '\n"
    "      f'({100*cooling_kwh/total_kwh:.1f}%)')\n"
    "print(f'  Heating (HDD):       {heating_kwh:>10,.0f} kWh '\n"
    "      f'({100*heating_kwh/total_kwh:.1f}%)')\n"
    "print(f'  Total HVAC:          '\n"
    "      f'{cooling_kwh + heating_kwh:>10,.0f} kWh '\n"
    "      f'({100*hvac_frac:.1f}% of total)')\n\n"
    "# Scatter plot\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n"
    "axes[0].scatter(daily_full['temp_f_avg'], daily_full['day_kwh'],\n"
    "                alpha=0.5, s=15, color='#1976D2')\n"
    "T_range = np.linspace(40, 100, 100)\n"
    "cdd = np.clip(T_range - 65, 0, None)\n"
    "hdd = np.clip(65 - T_range, 0, None)\n"
    "fitted = a + b * cdd + c * hdd\n"
    "axes[0].plot(T_range, fitted, 'r-', linewidth=2, label='Fit')\n"
    "axes[0].axvline(65, color='gray', linestyle='--', alpha=0.6,\n"
    "                label='Balance point (65 F)')\n"
    "axes[0].set_xlabel('Daily avg temperature (F)')\n"
    "axes[0].set_ylabel('Daily energy (kWh)')\n"
    "axes[0].set_title('Q6b - Load vs Temperature (real weather)')\n"
    "axes[0].legend(fontsize=9)\n\n"
    "# Compare estimates: 10th-pct baseline (Q6) vs regression (Q6b)\n"
    "axes[1].bar(['10th-pct baseline\\n(Q6 first-order)',\n"
    "             'Weather regression\\n(Q6b)'],\n"
    "            [100 * monthly['hvac_kwh'].sum() / annual_total,\n"
    "             100 * hvac_frac],\n"
    "            color=['#EF5350', '#43A047'])\n"
    "for i, v in enumerate([100*monthly['hvac_kwh'].sum()/annual_total,\n"
    "                       100*hvac_frac]):\n"
    "    axes[1].text(i, v + 1, f'{v:.1f}%', ha='center', fontsize=11,\n"
    "                 fontweight='bold')\n"
    "axes[1].set_ylabel('HVAC as % of annual energy')\n"
    "axes[1].set_title('Q6b - Estimate comparison')\n"
    "axes[1].set_ylim(0, max(50, hvac_frac*105 + 5))\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# ─────────────────────────────────────────────────────────────────────────────
# C18b - Q7b markdown: real PV
# ─────────────────────────────────────────────────────────────────────────────
C18b_md = md(
    "### Q7b — PV impact using REAL 300 kW profile\n\n"
    "Now with the actual PVWatts-style profile for Puente Hills, CA "
    "(15-min, 300 kW AC, peak ~232 kW after inverter clipping, annual "
    "generation ~470 MWh, 23% capacity factor).\n\n"
    "**Three accounting quantities** — PV export DOES affect the bill:\n"
    "1. **Billed net-import** = `max(0, load − PV)`, billed at retail TOU\n"
    "2. **Export kWh** = `max(0, PV − load)`, credited at NEM 3.0 rates\n"
    "3. **Self-consumption** = `min(load, PV)`, offsets retail rate directly\n\n"
    "Under **NEM 3.0** (default since April 2023) export credit is roughly "
    "$0.08/kWh (wholesale-linked, varies by hour and month). I use a flat "
    "$0.08/kWh proxy — a more rigorous answer would use the SCE NEM 3.0 "
    "hourly export rate matrix."
)

# ─────────────────────────────────────────────────────────────────────────────
# C18c - Q7b code: real PV
# ─────────────────────────────────────────────────────────────────────────────
C18c_code = code(
    "df_solar_real = load_real_solar()\n"
    "print(f'Real PV profile: {len(df_solar_real):,} rows, '\n"
    "      f'peak {df_solar_real[\"pv_kw\"].max():.1f} kW, '\n"
    "      f'annual {df_solar_real[\"pv_interval_kwh\"].sum():,.0f} kWh')\n\n"
    "df_pv = apply_real_solar(df, df_solar_real)\n"
    "# tou_period + is_trd are already carried over via the merge in apply_real_solar\n\n"
    "annual_gross_load = df['interval_kwh'].sum()\n"
    "annual_pv_kwh = df_pv['pv_interval_kwh'].sum() if 'pv_interval_kwh' in df_pv.columns else df_solar_real['pv_interval_kwh'].sum()\n"
    "annual_net_load = df_pv['net_interval_kwh'].sum()\n"
    "annual_export = df_pv['export_interval_kwh'].sum()\n"
    "annual_selfcons = annual_pv_kwh - annual_export\n\n"
    "print()\n"
    "print(f'ENERGY FLOWS with real 300 kW PV:')\n"
    "print(f'  Load (baseline):     {annual_gross_load:>10,.0f} kWh')\n"
    "print(f'  PV generation:       {annual_pv_kwh:>10,.0f} kWh')\n"
    "print(f'  Self-consumption:    {annual_selfcons:>10,.0f} kWh '\n"
    "      f'({100*annual_selfcons/annual_pv_kwh:.1f}% of PV)')\n"
    "print(f'  Export to grid:      {annual_export:>10,.0f} kWh '\n"
    "      f'({100*annual_export/annual_pv_kwh:.1f}% of PV)')\n"
    "print(f'  Net grid import:     {annual_net_load:>10,.0f} kWh '\n"
    "      f'({100*(1-annual_net_load/annual_gross_load):.1f}% reduction)')\n\n"
    "# Rebill with real net demand\n"
    "bill_pv_real = bill_from_scenario(\n"
    "    df_pv, demand_col='net_demand_kw',\n"
    "    energy_col='net_interval_kwh', tariff=tariff,\n"
    ")\n\n"
    "# Three savings numbers\n"
    "billed_savings = (bill['total_usd'] - bill_pv_real['total_usd']).sum()\n"
    "export_credit = annual_export * 0.08\n"
    "total_with_credit = billed_savings + export_credit\n\n"
    "print()\n"
    "print(f'ANNUAL BILL IMPACT (real 300 kW PV):')\n"
    "print(f'  Billed net-import savings:       ${billed_savings:>10,.0f}/yr')\n"
    "print(f'  NEM 3.0 export credit (@$0.08):  ${export_credit:>10,.0f}/yr')\n"
    "print(f'  TOTAL (with export credit):      ${total_with_credit:>10,.0f}/yr')\n\n"
    "compare_pv = pd.DataFrame({\n"
    "    'peak_kW_baseline':    bill['peak_demand_kw'].round(1),\n"
    "    'peak_kW_with_realPV': bill_pv_real['peak_demand_kw'].round(1),\n"
    "    'kWh_baseline':        bill['energy_kwh'].round(0),\n"
    "    'kWh_with_realPV':     bill_pv_real['energy_kwh'].round(0),\n"
    "    'bill_baseline':       bill['total_usd'].round(0),\n"
    "    'bill_with_realPV':    bill_pv_real['total_usd'].round(0),\n"
    "})\n"
    "compare_pv['bill_delta'] = (compare_pv['bill_baseline']\n"
    "                            - compare_pv['bill_with_realPV']).round(0)\n"
    "print()\n"
    "print('Q7b - Monthly impact (real PV):')\n"
    "print(compare_pv)\n\n"
    "# Chart\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
    "axes[0].bar(compare_pv.index - 0.2, compare_pv['peak_kW_baseline'], 0.4,\n"
    "            label='Baseline', color='#455A64')\n"
    "axes[0].bar(compare_pv.index + 0.2, compare_pv['peak_kW_with_realPV'],\n"
    "            0.4, label='With real 300 kW PV', color='#FDD835')\n"
    "axes[0].set_xlabel('Month')\n"
    "axes[0].set_ylabel('Peak demand (kW)')\n"
    "axes[0].set_title('Q7b - Peak: baseline vs real PV')\n"
    "axes[0].legend()\n"
    "axes[0].set_xticks(range(1, 13))\n\n"
    "axes[1].bar(compare_pv.index - 0.2, compare_pv['bill_baseline'], 0.4,\n"
    "            label='Baseline', color='#455A64')\n"
    "axes[1].bar(compare_pv.index + 0.2, compare_pv['bill_with_realPV'], 0.4,\n"
    "            label='With real PV', color='#FDD835')\n"
    "axes[1].set_xlabel('Month')\n"
    "axes[1].set_ylabel('Monthly bill ($)')\n"
    "axes[1].set_title('Q7b - Bill: baseline vs real PV')\n"
    "axes[1].legend()\n"
    "axes[1].set_xticks(range(1, 13))\n"
    "axes[1].yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(\n"
    "    lambda x, _: f'${x:,.0f}'))\n"
    "plt.tight_layout()\n"
    "plt.show()"
)

# ─────────────────────────────────────────────────────────────────────────────
# C20b - Q8b markdown: MILP battery
# ─────────────────────────────────────────────────────────────────────────────
C20b_md = md(
    "### Q8b — MILP battery dispatch (upper bound)\n\n"
    "The rule-based dispatch above is a **lower bound**. Below I run a "
    "**linear program (LP)** that finds the *optimal* charge/discharge "
    "schedule for the same 250 kWh / 100 kW battery.\n\n"
    "**Solver:** `cvxpy` with HIGHS backend, 12 independent monthly "
    "sub-problems.\n\n"
    "**Objective (per month):**\n\n"
    "```\n"
    "minimize:\n"
    "    Σ_t (rate[t] + FRC + MCAM) × grid[t] × dt      # energy cost\n"
    "  + FRD_rate × peak_kw                              # all-time demand\n"
    "  + TRD_rate × trd_peak_kw                          # season demand\n"
    "```\n\n"
    "**Constraints:**\n"
    "- `grid[t] = load[t] − discharge[t] + charge[t]`\n"
    "- `grid[t] ≥ 0` (no battery-to-grid export)\n"
    "- `grid[t] ≤ peak_kw` (FRD envelope)\n"
    "- `grid[t] ≤ trd_peak_kw` for TRD hours only\n"
    "- SoC balance: `soc[t+1] = soc[t] + η·charge − (1/η)·discharge`\n"
    "- Power ≤ 100 kW, capacity ≤ 250 kWh\n\n"
    "**Note:** This is an LP not MILP — efficiency losses prevent "
    "simultaneous charge+discharge without needing binary variables. If "
    "solve had issues, we would add binary switch vars (proper MILP)."
)

# ─────────────────────────────────────────────────────────────────────────────
# C20c - Q8b code: MILP battery
# ─────────────────────────────────────────────────────────────────────────────
C20c_code = code(
    "print('Solving monthly LPs (may take 15-30 sec)...')\n"
    "df_milp = simulate_battery_milp(df, capacity_kwh=250, power_kw=100,\n"
    "                                efficiency=0.90, tariff=tariff)\n"
    "# tou_period + is_trd already present from df.copy() in simulate_battery_milp\n\n"
    "annual_discharge_milp = df_milp.loc[df_milp['battery_kw'] > 0,\n"
    "                                    'battery_kw'].sum() * 0.25\n"
    "annual_charge_milp = -df_milp.loc[df_milp['battery_kw'] < 0,\n"
    "                                  'battery_kw'].sum() * 0.25\n"
    "print(f'Annual battery discharge (MILP): {annual_discharge_milp:,.0f} kWh')\n"
    "print(f'Annual battery charge (MILP):    {annual_charge_milp:,.0f} kWh')\n\n"
    "bill_milp = bill_from_scenario(\n"
    "    df_milp, demand_col='net_demand_kw',\n"
    "    energy_col='net_interval_kwh', tariff=tariff,\n"
    ")\n\n"
    "# Compare rule-based vs MILP\n"
    "compare_milp = pd.DataFrame({\n"
    "    'baseline':    bill['total_usd'].round(0),\n"
    "    'rule_based':  bill_bat['total_usd'].round(0),\n"
    "    'milp':        bill_milp['total_usd'].round(0),\n"
    "    'peak_base':   bill['peak_demand_kw'].round(1),\n"
    "    'peak_rule':   bill_bat['peak_demand_kw'].round(1),\n"
    "    'peak_milp':   bill_milp['peak_demand_kw'].round(1),\n"
    "})\n"
    "compare_milp['savings_rule'] = (compare_milp['baseline']\n"
    "                                - compare_milp['rule_based']).round(0)\n"
    "compare_milp['savings_milp'] = (compare_milp['baseline']\n"
    "                                - compare_milp['milp']).round(0)\n"
    "print()\n"
    "print('Q8b - Rule-based vs MILP dispatch (250 kWh / 100 kW battery):')\n"
    "print(compare_milp[['baseline', 'rule_based', 'milp',\n"
    "                    'savings_rule', 'savings_milp']])\n\n"
    "total_rule = compare_milp['savings_rule'].sum()\n"
    "total_milp = compare_milp['savings_milp'].sum()\n"
    "print()\n"
    "print(f'ANNUAL SAVINGS COMPARISON:')\n"
    "print(f'  Rule-based dispatch:   ${total_rule:>7,.0f}/yr')\n"
    "print(f'  MILP dispatch (upper): ${total_milp:>7,.0f}/yr')\n"
    "if total_rule > 0:\n"
    "    print(f'  MILP uplift:           '\n"
    "          f'{total_milp/total_rule:.1f}x better')\n\n"
    "# Chart: monthly peaks, rule vs MILP\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 4))\n"
    "w = 0.28\n"
    "x = compare_milp.index\n"
    "axes[0].bar(x - w, compare_milp['peak_base'], w,\n"
    "            label='Baseline', color='#455A64')\n"
    "axes[0].bar(x, compare_milp['peak_rule'], w,\n"
    "            label='Rule-based battery', color='#FFA726')\n"
    "axes[0].bar(x + w, compare_milp['peak_milp'], w,\n"
    "            label='MILP battery', color='#26A69A')\n"
    "axes[0].set_xlabel('Month')\n"
    "axes[0].set_ylabel('Peak demand (kW)')\n"
    "axes[0].set_title('Q8b - Peak: baseline vs rule vs MILP')\n"
    "axes[0].legend(fontsize=9)\n"
    "axes[0].set_xticks(range(1, 13))\n\n"
    "axes[1].bar(x - w, compare_milp['baseline'], w,\n"
    "            label='Baseline', color='#455A64')\n"
    "axes[1].bar(x, compare_milp['rule_based'], w,\n"
    "            label='Rule-based', color='#FFA726')\n"
    "axes[1].bar(x + w, compare_milp['milp'], w,\n"
    "            label='MILP', color='#26A69A')\n"
    "axes[1].set_xlabel('Month')\n"
    "axes[1].set_ylabel('Monthly bill ($)')\n"
    "axes[1].set_title('Q8b - Bill: baseline vs rule vs MILP')\n"
    "axes[1].legend(fontsize=9)\n"
    "axes[1].set_xticks(range(1, 13))\n"
    "axes[1].yaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(\n"
    "    lambda x, _: f'${x:,.0f}'))\n"
    "plt.tight_layout()\n"
    "plt.show()"
)


# ─────────────────────────────────────────────────────────────────────────────
# Assemble
# ─────────────────────────────────────────────────────────────────────────────
nb.cells = [
    C1, C2, C3, C4, C5, C6, C7, C8, C9, C10,
    C11, C12, C13, C14, C15, C16,
    # Real weather regression injected after Q6 code
    C16b_md, C16c_code,
    C17, C18,
    # Real PV cell injected after Q7 code
    C18b_md, C18c_code,
    C19, C20,
    # MILP battery injected after Q8 code
    C20b_md, C20c_code,
    C21,
]

out = Path(__file__).parent / "analyst_exercise.ipynb"
with open(out, "w", encoding="utf-8") as f:
    nbf.write(nb, f)

print(f"Notebook written: {out}  ({len(nb.cells)} cells)")
